version: '3.7'
services:
  watcher:
    network_mode: bridge
    build:
      context: ./
      dockerfile: Dockerfile
    image: watcher
    restart: always
    stdin_open: true
    tty: true
    working_dir: /usr/src/watcher
    shm_size: '2gb'