version: '3.3'
services:
  watcher:
    network_mode: bridge
    build:
      context: ./watcher
      dockerfile: ./Dockerfile
    image: watcher
    restart: always
    stdin_open: true
    tty: true
    working_dir: /usr/src/watcher
    shm_size: '2gb'
  runner:
    network_mode: bridge
    build:
      context: ./runner
      dockerfile: ./Dockerfile
    image: runner
    restart: always
    stdin_open: true
    tty: true
    working_dir: /usr/src/runner