version: '3.3'
services:
  watcher:
    build:
      context: ./watcher
      dockerfile: ./Dockerfile
    env_file:
      - .env
    image: watcher
    restart: always
    stdin_open: true
    tty: true
    working_dir: /usr/src/watcher
    shm_size: '2gb'
    networks:
      - kanatran
  runner:
    build:
      context: ./
      dockerfile: ./runner/Dockerfile
    env_file:
      - .env
    restart: always
    stdin_open: true
    tty: true
    working_dir: /usr/src/runner
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - kanatran

networks:
  kanatran:
    external: true
