version: '3.3'
services:
  watcher:
    network_mode: bridge
    build:
      context: ./watcher
      dockerfile: ./Dockerfile
    env_file:
      - .env
    image: watcher
    restart: always
    stdin_open: true
    tty: true
    working_dir: /usr/src/watcher
    shm_size: '2gb'
  runner:
    network_mode: bridge
    build:
      context: ./
      dockerfile: ./runner/Dockerfile
    env_file:
      - .env
    image: runner
    restart: always
    stdin_open: true
    tty: true
    working_dir: /usr/src/runner
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock