name: Build Watcher

on: workflow_dispatch

jobs:
  build_watcher:
    runs-on: ubuntu-latest
    steps:
      - name: Init
        run: |
          echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u ${{ secrets.CR_USERNAME }} --password-stdin
      - name: Build
        run: |
          make build container=watcher
      - name: Publish
        run: |
          docker tag watcher ghcr.io/LiveTL/kanatran:latest
          docker push ghcr.io/LiveTL/kanatran:latest