name: Deploy to Production

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge dev branch
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          from_branch: develop
          target_branch: master
          github_token: ${{ github.token }}

      - name: Dispatch Runner Build
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Build Runner
          token: ${{ secrets.DISPATCH_KEY }}

      - name: Dispatch Watcher Build
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Build Watcher
          token: ${{ secrets.DISPATCH_KEY }}
