name: Deploy to Production

on:
  # push:
    # branches:
    #   - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.PROD_SSH_KEY }}
          name: id_rsa
          known_hosts: ${{ secrets.PROD_KNOWN_HOSTS }}
          if_key_exists: replace

      - name: Run Deploy Script
        run: |
          ssh ${{ secrets.PROD_USERNAME }}@${{ secrets.PROD_IP }} \
            "cd /livetl/kanatran/controller; expect expect.exp ${{ secrets.PROD_PASSWORD }}"
