name: Deploy to Production

on:
  # push:
    # branches:
    #   - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: webfactory/ssh-agent@v0.5.1
        with:
          ssh-private-key: ${{ secrets.PROD_SSH_KEY }}

      - name: Run Deploy Script
        run: |
          ssh ${{ secrets.PROD_SSH }} "cd /livetl/kanatran/controller; expect expect.exp ${{ secrets.PROD_PASSWORD }}"
